### ISSUE TITLE
Missing copyright holder in LICENSE

### ISSUE THREAD

**Issue by alamers** [adewg/ICAR#105]
in our LICENSE file, there is still a placeholder for the copyright holder:
`Copyright [yyyy] [name of copyright owner]`

I guess this should read 
`Copyright 2020 ICAR`.

Also, it is advised to have a copyright notice in each and every file... I guess that is a bit too much?

**Comment by cookeac** [comment]
I had assumed that the bottom section of the LICENCE file described how licence and copyright information should be included into source code or other files, and that the LICENCE file itself should not be edited so that GitHub could recognise it was the standard Apache 2.0 licence.
If that is the case, then that text and link to the licence should be included in the README.md file instead. However, perhaps I misunderstood this!

**Comment by alamers** [comment]
I just had a look at (for example) Docker: https://github.com/docker/compose/blob/master/LICENSE

They have done this as well (although I see I forgot to remove the instructional part in the pull request, need to remove that as well).
