### ISSUE TITLE
Guidance on use of schema/id and name pairs within API

### ISSUE THREAD

**Issue by mgjoyce** [adewg/ICAR#107]
The inclusion of both scheme/id and name in the schema for Breeding values was noticed when discussing issue: https://github.com/adewg/ICAR/issues/89

Questions raised during discussion:
1. Is the duplication an aide or a hindrance to the usability of the standard?
2. Is the Name essentially a Default name?  e.g. in the absence of a i18n/l10n/Locale resource to resolve the name of an entity with a given scheme/id for the Locale then the default name would be displayed).
3. Should we adopt a method for making i18n/l10n part of the APIs?

Ideas for discussion (not exhaustive)
- Guidance to producers and consumers of APIs built to the standard
- Adoption of a i18n/l10n mechanism withing the ADE API.
- ...?

Another example:
Animal Health Treatments - Diagnosis (Diagnosis Code and Name)

**Comment by cookeac** [comment]
It seems to me there are several issues at play here, as @mgjoyce has noted:
1. Potential duplication (and therefore potential for conflict) between the definitive scheme/id for a breeding value, evaluation, product, or other resource, and the name.
* My opinion is that despite this risk, the Name provides a good shorthand default display name.

2. How do we deal with translation? Is the Name localised/internationalised, or is it a default name, either in English or the language of the data provider? If the latter, what is the language?
* One approach recommended in the W3C Strings on the Web draft https://www.w3.org/TR/string-meta/ is to add a plain-literal to the end of the string (https://www.w3.org/TR/rdf-plain-literal/). So a breeding value name could be "Protein@en" with the literal indicating the language (in this example English).

3. Do we want to support multiple translations for a name in the data? For instance, an array of possible string values in different languages. Schema.org has taken this approach for some schemas.
* It feels to me like this would generate a lot of redundant string data given the use in what could be hundreds or thousands of events for hundreds or thousands of animals.

**Comment by alamers** [comment]
I see a number of usages for this but don't feel like this is the proper solution; let's look at the use cases (maybe I am missing some). It is trivial for a data source to provide some display name for a data source in e.g. English, but as Andrew indicates: it may add up to quite some additional redundant traffic. 

Adding a (display) name to a message will:

1. improve the self-explanatory nature of the message / reduces chance of misinterpretation
2. shortcut the need to translate a key into a display value
 
1: Hopefully the use of enums and scheme values would already give a developer a good idea on what the data represents. Not in all scheme's the values are easily interpreted and sometimes require lookup tables. In these cases a name would be beneficial but it feels like compensating for that scheme's opaqueness. Is that our role? Should be try to find standard names? Can we not work with those scheme's to evolve beyond opaque numbers?

2: Since the enum values are technical names, and thus stable, any i18n should be based on these. i18n is also more of a representation issue than a data standard. Since the data source is not necessarily the same as the consumer, they may well reside in different countries, it is unreasonable to expect to provide multiple translations in all appropriate languages. That burden will always land on the application, it is not reasonable to shift this to a data source. It is only useful for when source and consumer share their (single) locale.

In my opinion, the added value is very minimal since it feels like a compensation for opaque scheme's. 

In general, I would limit the scope of ICAR standardization to provide _keys_ that can be used for i18n, but not try to provide i18n ourselves.

**Comment by alamers** [comment]
This ticket has been open for a while: I think the outcome of this ticket should be some principles on how/if ICAR ADE deals with i18n, specifically in relation with enums. 

I am not sure if there is a consensus on this yet, although we may have it in our current practice. So maybe a good topic to discuss in next meeting? @cookeac, could we add this to the agenda?
