### ISSUE TITLE
ICAR Milking Type Code might be misleading

### ISSUE THREAD

**Issue by ghost** [adewg/ICAR#113]
When providing an MilkVisitEventResource, we can supply a milkingType with it. The possible enum values are listed in https://github.com/adewg/ICAR/blob/ADE-1/enums/icarMilkingTypeCode.json

As the only possible values are "Manual" and "Automatic", this might be slightly misleading. With a milking robot, you can still attach a cow manually in some models, and in conventional milking, the milking process is most of the time automatic.

I'd propose (unfortunately as a breaking change for a new version) to either define something like "Robot" and "Conventional" as values or be even more specific like "Robot Auto Attach", "Robot Manual Attach", "Conventional" (and maybe other values).

**Comment by ghost** [comment]
To add some more complexity: Automatic might even be more ambiguous as it does not describe the type of milking parlor, e.g. it could be an automatic rotor or an automatic robot for free cow traffic.

**Comment by cookeac** [comment]
This particular enumeration dates from the original XML specification (developed before I was involved with the group). 

However, on investigation, I believe this reflects the differentiation in the ICAR Guidelines between "fully automatic" systems that collect data such as milk weights and any other metrics "without manual intervention" and other systems where manual intervention occur in some way. So it is not trying to define the device (there is a device object for this), but simply which rules are expected to be used.

Section 2 of the Guidelines (milk recording), clause 6.8 covers some of this, and section 11 (milk recording devices) also covers this and refers to the ISO requirements for such devices.
* https://www.icar.org/Guidelines/02-Overview-Cattle-Milk-Recording.pdf
* https://www.icar.org/Guidelines/11-Milk-Recording-Devices.pdf

Bearing this in mind, I recommend that this particular field be left as it is (because it reflects the guidelines) and if we need to differentiate the methods of milking and attachment in more detail, then we either identify capabilities in the Device object, or add another field for milking equipment type.
