### ISSUE TITLE
Release timeframe for Issue 1.1

### ISSUE THREAD

**Issue by cookeac** [adewg/ICAR#128]
The technical working group has made good progress on a number of additions that could comprise the version 1.1 release of ADE.
These will be non-breaking changes, so there is no reason to unduly delay the release.

Therefore there are two questions to answer:
1. What is the **desired timeframe** for ADE 1.1 release?
2. Are there **required features** that need to be included or resolved before version 1.1. can be released?

Please comment with your feedback.

**Comment by ghost** [comment]
From my point of view, having #88, #110 and #125 would be great.

Clearing #108 by a comment is simple for 1.1, so we could add it.

Having something for #111 would be very great, but I think we need some more discussion here. If possible, we will come forward with a proposal.

**Comment by alamers** [comment]
From a communication point of view, smaller but more frequent releases would be better; it shows progress and shows that ADE can keep up with implementations. Note that a release is nothing more than just a version number, so it should be relatively light weight.

Since it is quite unpredictable what features are available when, due to all the volunteers working on different things, I'd suggest to release whenever we have something interesting. Or, to put it differently, not to wait with a release for a specific feature. That also prevents implementations from growing their own solutions.

Having said that, a release should be substantial as well; not sure what the 'minimal' change should be. But at least one or two new messages feels like a reasonable minimal scope?

**Comment by ghost** [comment]
I second Arjans point with a slight modification: non-breaking changes should be introduced frequently. However, if we have breaking changes, from that point on we have to see whether we want to support subsequent non-breaking changes in more than one version. That will induce some work... Major versions should contain a certain amount of breaking changes until release as otherwise we might have too many versions out there that are in use and have to be supported. I expect that major version changes will be picked up not very quickly in the field due to the effort involved on all sides.

**Comment by erwinspeybroeck** [comment]
I would like to add gestations [https://github.com/adewg/ICAR/issues/121](url)

**Comment by ahokkonen** [comment]
Would it be good to use labels for the issues planned for next release/version?
Like "selected-for-release" or similar. It might be easier to track and react on discussion for ones which are prioritized for release.
