### ISSUE TITLE
have a decision on how to implement the schema's

### ISSUE THREAD

**Issue by erwinspeybroeck** [adewg/ICAR#15]
- animal number
- location/herd
- customer
- ...

**Comment by cookeac** [comment]
My recommendation (which we have done in other schemas for other purposes is):

1. Be consistent. Use the same structures for all such identifiers (animal, location, herd, facility...)
2. Use a URI. This doesn't have to be a live URL with content. For instance "standards.iso.org/iso/11785" (ISO URI for the electronic ID numbering specification) and "id.gs1.org/gtin" (GS1 scheme for the global trade item number).

**Comment by cookeac** [comment]
After discussion:
a. If schemes and IDs are to be included in URLs, they will need to be URL encoded because some contain / and : for example.
b. It would be nice if they fit naturally or are readily human readable. For instance, we prefer ubn.business.gov.nl to URL encoding business.gov.nl/ubn. 
c. We propose to put an INFORMATIVE registry into this specification (which people can update by pull request) so scheme operators can publicise their preferred name.
d. We will work with initial active parties to come up with good names for their schemes so that other people can model their scheme names on these.

**Comment by cookeac** [comment]
We discussed this further and will recommend people consider the Java/Google style [Reverse Domain Name](https://en.wikipedia.org/wiki/Reverse_domain_name_notation) notation.
So "org.interbull.id" or "nl.gov.ubn" or similar.

**Comment by alamers** [comment]
Since the scheme's are INFORMATIVE, there will be no definitive set of scheme's. As such, we do not need to have a decision on which scheme's there are. As Andrew stated above, we do have recommendations on how they should look.
