### ISSUE TITLE
endpoint /animalSets uses inconsistent syntax

### ISSUE THREAD

**Issue by alamers** [adewg/ICAR#179]
Shouldn't `/locations/{location-scheme}/{location-id}/animalSets` be named `/locations/{location-scheme}/{location-id}/animal-sets`?

**Comment by ahokkonen** [comment]
I agree with that proposal. I don't think this correction will be considered as breaking change, or? :)

**Comment by cookeac** [comment]
I also agree with this proposal, and I note that the exampleURLScheme.json file is effectively INFORMATIVE rather than NORMATIVE - it provides an example or recommended scheme (in contrast to data elements where a breaking change could break software). 

However, because some implementers may have built on this example, I recommend that we document this change clearly when publishing the release with this change.

**Comment by cookeac** [comment]
Fixed in #186
