### ISSUE TITLE
Missing types in MovementBirthEventResource

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#183]
Hi, 

where are missing som types to descripe following: 

StateofbirthType:
Defective calf
Live calf
Live calf, born prematurely
Died within 1 day
Died after 1 day
Stillborn
Abortion
Culled at birth

SizeatbirthType: 
Little
Below average
Above average
Big

It is not possible for us to receive Birthregistration without theese information

BR

**Comment by dirbSEGES** [comment]
I found reproparturition

**Comment by cookeac** [comment]
The ReproParturition event is to capture information relating to the birth, while the MovementBirth event is to register the progeny (for systems that do this separately from providing progeny details as part of a parturition event).

The ReproStatusObserved event is to capture information relating to abortions.

It would appear there are two suggestions here:

- Ability to capture additional (but ideally structured) information about the parturition - the first list above.
- Ability to capture "size" as opposed to birth weight, for the progeny (or is this intended as an observation related to the dam, rather than the progeny - how is it used in animal evaluation?)

If these are international needs, and we can define the set of values, they could be added as enumerations. Otherwise my suggestion is for a localised use they can be added as an extension (the specification and JSON support this).

**Comment by dirbSEGES** [comment]
Ok, i understand. We have the same system with separate registrations. 

Yes - i have 2 suggestions. About the suggestions, we use the informations in the calculations of breedingvalues. 

I have a 3. suggestions to describe  the "calvingprocess". (Maybe it is what calvingEase in the ReproParturitionressource describes, but there are not any selections yet) Also used in the calculation of breedingvalues. 

Easy without help
Easy with help
Difficult without veterinary care
Difficult with veterinary care
Cesarean section

I'm not sure if it's a international need, but it is a requirements in our system when a calving is registered. 

Can there be a guidence how to make a local extension for the ReproParturition?

**Comment by ahokkonen** [comment]
Personally I see that this should be defined as part of "**calvingEase**" codes. 
Currently in icarReproParturitionEventResource this field is defined as "open" string type, but in my opinion it should be defined with own enum type including values proposed by @dirbSEGES

**Comment by erwinspeybroeck** [comment]
We are talking about the calvingEase field indeed. We discussed it in the past, but I think there was no consensus to make it an enum as such, since vaues can differ regarding country.

**Comment by dirbSEGES** [comment]
We will make local additions for Birthsize and Stateofbirth. And use the enumeration for calvingEase that will be defined in the discussion in #185 

I will close this discussion. Thank you.
