### ISSUE TITLE
Add icarConsignmentType on MovementDeathEventResource

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#192]
Hi, 

in case of death/culled we need registrate a destinationlocation(locationid of disposal operator)  . So could ConsigmentType be added?

Another solution could be that DepartureKindType was extented with 2 ekstra selections Death(deceased) and Culled?

**Comment by ahokkonen** [comment]
In NCDX data exchange solution we are solving death registration via "Departure" event and we do have these statuses for departure type/reason (for example Died, Lost, etc.)

In death event we already have a field for "disposalOperator", but seems like it is not enough for your needs?

**Comment by dirbSEGES** [comment]
We also handle death/culled as a depature in our system. So from our side it could really good if the DepatureKindType is extented with 2 extra selection death and culled. Then there are no resaon to add extra fields on DeathEvent.

**Comment by ahokkonen** [comment]
Personally I would prefer to use DeathEvent for registering death, but we might need to extend/adopt it for our requirements

**Comment by dirbSEGES** [comment]
If we need to used the DeathEvent we will set a very low standard for the data we will recieve. We don´t want to go that way.

**Comment by cookeac** [comment]
Before getting into the syntax of the fields, you need to be clear about the semantics of what you are expressing by the choice of messages:
- If animals are leaving the location **alive**, you must use a *Departure* event.
- If animals have **died or been euthanised** on the location, you must use a *Death* event.

You can then address the additional data fields that are required in the relevant event.
For instance, the death event has:
- *deathReason* - this includes natural reasons for deaths (including alignment with checklists or categories used in some national recording systems), and also includes culling.
- *disposalOperator* - based on the fields in most movement documents for the disposal destination or service
- *disposalReference* - where a receipt or movement identifier is required for the disposal
- *explanation* - text description of death reason - unlikely to be useful to you for coding to support analysis.

I think there is a good case that deaths should optionally support **icarConsignmentType** (as the arrival and departure events do). This would allow more detailed transport and destination information to be captured on the removal of the dead animals. I would be happy to recommend this at the next technical group meeting.

If the animals leave the farm alive, then the departure event should be used. If you were culling animals, I would anticipate that:
- *departureKind* would be Sale, Slaughter, or Other depending on the mechanism of removal
- *departureReason* defines a number of reasons for removing animals. "Culling" is a general decision likely to be based on any of those reasons (for instance, culled because of health, fertility, age, superfluous...). If you are culling animals and don't know the specific reason, then Other is probably appropriate.

**Comment by dirbSEGES** [comment]
I do understand the semantics of the 2 messages. And I´m trying to fit our system into it. 

So if we must use Death event i suggest a field deathKind with the selection: 

dead (passed away - expression indicating that the animal died without human intervention)
euthanised

We need to differentiate between these 2 kinds of "death" . 

It will really help a long way if icarConsignmentType is supported in the deathEvent, then we can recieve the destination location in with right id and scheme.

**Comment by cookeac** [comment]
At a recent meeting we discussed several options:
1. Merging Deaths and Departures - this would be a structural change that would be more suitable for a major version number change, although it could be achieved without breaking changes with appropriate documentation. It will not match recording systems in many countries (including national registration systems) where deaths are considered separate from movements.
2. Insisting that a Departure event is recorded after a Death, so that there are two events where animals may be registered on a farm (a birth/registration event or an arrival event), but only one event where they leave the farm. This will also not match recording systems where a death event is considered sufficent to remove the animal, or countries where on-premise disposal is allowed (extensive farms, small animals, or abattoirs).
3. Adding a *consignment* property that recognises that in some cases recording a death will require recording the destination of movement for the corpse. This is my preference but we will discuss at the next meeting.

I agree that a deathKind (or perhaps *deathMethod*?) should be defined. This might have two or three valid values:
- natural (includes all natural causes of death that do not have human intervention to euthanise)
- accident (i.e. human/machine induced but not intentional)
- euthanised

**Comment by dirbSEGES** [comment]
Hi, 
We are fine with using Death, if consignment and deathMethod is added to the resource.

**Comment by cookeac** [comment]
Fixed in #204
