### ISSUE TITLE
Remove DoNotBreed from animal

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#213]
Hi, 

Do you have any suggestion how to remove a DoNotBreed label from an animal? 

When a client are using the DoNotBreed ressource, it sets a DNB label to an animal, but the ressource, as I understand, can not remove it again?

**Comment by cookeac** [comment]
Maybe this should be a BreedControl event, so you can set it to Do Not Breed, or Allow Breeding.
@erwinspeybroeck to investigate how they are using this event.

**Comment by dirbSEGES** [comment]
We like the idea of a BreedControl event.

**Comment by erwinspeybroeck** [comment]
We use a DELETE event to switch from the status do not breed to allow breeding.
If someone would need history to keep track of the changes, it can be done by storing the delete event to keep track of the changed status of the animal

**Comment by cookeac** [comment]
Proposing that we add a boolean *doNotBreed* attribute to the icarReproDoNotBreedEventResource. This allows an observer to turn off the reproductiveStatus "DoNotBreed". For backwards compatibility, this will be nullable and true by default, so that it must be explicitly specified as false to clear the DoNotBreed status.

**Comment by dirbSEGES** [comment]
Fine solution :-)
