### ISSUE TITLE
nullable declaration is not working correctly for reference types

### ISSUE THREAD

**Issue by ahokkonen** [adewg/ICAR#214]
Seems like nullable field declaration for reference types is not valid and during code generation property stays as non-nullable despite "nullable": true.

Example from [icarMetaType.json](https://raw.githubusercontent.com/adewg/ICAR/ADE-1/types/icarMetaDataType.json):

```jsonc
    "created": {
      "$ref": "../types/icarDateTimeType.json",
      "nullable": true
    },
```
non-nullable date type gets generated as a result. 
Not sure if this is a generator issue or invalid OpenAPI markup for these kind on declaration. It look like valid way of defining nullable reference type would be:

**OpenAPI 3.0**
```jsonc
"created": {
    "nullable": true,
    "allOf": [
        { "$ref": "../types/icarDateTimeType.json" }
    ]
}
```

**OpenAPI 3.1**
```jsonc
"created": {
    "anyOf": [
        { "type": "null" },
        { "$ref": "../types/icarDateTimeType.json" }
    ]
}
```

I haven't tested that myself yet.

**Comment by AndreasSchultzGEA** [comment]
Our generating-process seems to cover this correctly:
` @ApiModelProperty(required = true, value = "udt:DateTimeType | A particular point in the progression of time together with relevant supplementary information.")
  @NotNull
  @Valid
  public OffsetDateTime getModified() {
    return modified;
  }
`

vs
` @ApiModelProperty(value = "udt:DateTimeType | A particular point in the progression of time together with relevant supplementary information.")
  @Valid
  public OffsetDateTime getCreated() {
    return created;
  }
`

**Comment by ahokkonen** [comment]
> Our generating-process seems to cover this correctly:
> `@ApiModelProperty(required = true, value = "udt:DateTimeType | A particular point in the progression of time together with relevant supplementary information.") @NotNull @Valid public OffsetDateTime getModified() { return modified; }`
> 
> vs
> `@ApiModelProperty(value = "udt:DateTimeType | A particular point in the progression of time together with relevant supplementary information.") @Valid public OffsetDateTime getCreated() { return created; }`

Are you using openapi-generator tools for this? Maybe this is an issue of .NET code generation...

**Comment by AndreasSchultzGEA** [comment]
Hi Anton,

yes that's the tool we use:

<groupId>org.openapitools</groupId>
<artifactId>openapi-generator-maven-plugin</artifactId>
<version>4.2.3</version>

**Comment by ahokkonen** [comment]
With some research, things around Nullable types gets even more complicated. With defining complex reference type having just a "nullable: true" is actually not right (and not spec compliant on OAS3.0), but somehow supported by various generators :) 

Here is a nice [issue to read ](https://github.com/OpenAPITools/openapi-generator/issues/5180) on "openapi-generator" project.

Had no luck with csharp generator producing proper nullable types only with "nullable: true", but when changed code to use "allOf" (I guess "oneOf" or "anyOf" will also do the trick) from my first message everything went smoothly through.

```jsonc
"created": {
    "nullable": true,
    "allOf": [
        { "$ref": "../types/icarDateTimeType.json" }
    ]
}
```
In some feedbacks this is also considered as a workaround and not a "fully official" OAS3.0 spec.

**Comment by cookeac** [comment]
Agreed, looking back through the JSON Schema specs, `"nullable": true` is ignored by JSON Schema, and we had started using it purely to support OpenAPI, based on assumptions from the YAML version of OpenAPI.
JSON Schema's solution is `allOf` for reference types as you have described, or for simple types:

`"type" : [ "string", "null" ]`

Of course, different versions of OpenAPI spec support different subsets of the JSON Schema spec, hence our confusion.

**Comment by ahokkonen** [comment]
Any opinion on if we should fix a declarations for those properties which meant to be nullable?

**Comment by AndreasSchultzGEA** [comment]
Has any one from the Java-users verified the result of OpenAPI 3.1 if we change the to '"type" : [ "string", "null" ]' and  
`"created": {
    "anyOf": [
        { "type": "null" },
        { "$ref": "../types/icarDateTimeType.json" }
    ]
}`
Just to avoid, that C# works, but Java and JavaScript not ...

**Comment by alamers** [comment]
I've just did some testing with Java. I specified 'created' date in the 'proper' 3.0 style as Anton proposed. The 'validFrom' (and other fields I left as-is.

Client generation with openapi-generator-cli-4.3.1 and openapi-generator-cli-5.2.0
In both cases, the field `private OffsetDateTime created` is replaced with `JsonNullable<OffsetDateTime> created = JsonNullable.<OffsetDateTime>of(null);`

The rationale behind the JsonNullable wrapper is, according to [OpenAPITools](https://github.com/OpenAPITools/jackson-databind-nullable):

_The JsonNullable wrapper shall be used to wrap Java bean fields for which it is important to distinguish between an explicit "null" and the field not being present. A typical usage is when implementing Json Merge Patch where an explicit "null"has the meaning "set this field to null / remove this field" whereas a non-present field has the meaning "don't change the value of this field"._

So, it seems that the original implementation leaves out this different interpretations of null. It probably works for most cases though.

Changing to the 'proper' 3.0 style means a compile time breaking change.

**Comment by ahokkonen** [comment]
I've performed my tests with various versions of openapi-generators and unless I had nullable declaration set as suggested for 3.0 (refer to my comment) the compiled result was incorrect. So, unfortunately, with using openapi-generator tool for .net specs needs to be adjusted.

I also has some tries with **autorest**, but seems like I need to look a bit deeper into the configuration docs :) With default setting compiled result was produced only for url APIs and not models/types. Maybe I need to merge the schemes first into one so autorest will pick all the defs from single file...

**Comment by ahokkonen** [comment]
> I've just did some testing with Java. I specified 'created' date in the 'proper' 3.0 style as Anton proposed. The 'validFrom' (and other fields I left as-is.
> 
> Client generation with openapi-generator-cli-4.3.1 and openapi-generator-cli-5.2.0
> In both cases, the field `private OffsetDateTime created` is replaced with `JsonNullable<OffsetDateTime> created = JsonNullable.<OffsetDateTime>of(null);`
> 
> The rationale behind the JsonNullable wrapper is, according to [OpenAPITools](https://github.com/OpenAPITools/jackson-databind-nullable):
> 
> _The JsonNullable wrapper shall be used to wrap Java bean fields for which it is important to distinguish between an explicit "null" and the field not being present. A typical usage is when implementing Json Merge Patch where an explicit "null"has the meaning "set this field to null / remove this field" whereas a non-present field has the meaning "don't change the value of this field"._
> 
> So, it seems that the original implementation leaves out this different interpretations of null. It probably works for most cases though.
> 
> Changing to the 'proper' 3.0 style means a compile time breaking change.

btw, @alamers, what if you try to switch off the "openApiNullable" in configuration and then compile? Looks like Jackson library is used by default for nullable as [stated](https://openapi-generator.tech/docs/generators/java/) in openapi-generator Java docs. This setting I assume leads to that strange declaration in a compiled  code.

**Comment by alamers** [comment]
I tested with that `openApiNullable` parameter and for 5.2.0 that generates the same code as before. For 4.3.1, the switch doesn't seem to do anything.

So, the proper '3.0' style works also for Java: either you get the JsonNullable wrapper (with the rationale as stated above), or you explicitly switch that off to get the same code back as we have now. That is, if you use the 5.2.0 generator.

**Comment by ahokkonen** [comment]
> I tested with that `openApiNullable` parameter and for 5.2.0 that generates the same code as before. For 4.3.1, the switch doesn't seem to do anything.
> 
> So, the proper '3.0' style works also for Java: either you get the JsonNullable wrapper (with the rationale as stated above), or you explicitly switch that off to get the same code back as we have now. That is, if you use the 5.2.0 generator.

Ok, maybe for the older version that switch wasn't just supported. So we can state that using latest version of the generator and proper OpenAPI 3.0 nullable declaration we'll get correct results in both languages (c# and java). Was there still something wrong for TypeScript? @AndreasSchultzGEA

**Comment by AndreasSchultzGEA** [comment]
TS is okay.

**Comment by ahokkonen** [comment]
back to that issue - should we work on correcting nullable declarations in all schemata for the next minor release (1.3?) and then provide a clear and proper descriptions on code generation (at least Java, .NET, TS)?

I can assign that task on myself and verify for .NET gens, but then I'll need an input from the others to make sure we'll get correct output for Java and TS :)

**Comment by AndreasSchultzGEA** [comment]
Hi Anton,

I'll try to find some time for this issue at the end of the week to check Java and TS.

Best regards,
Andreas Schultz
Senior Software Engineer
On-farm Applications
Farm Technologies | Digital Solutions and Services

Email
***@***.******@***.***>
Web
www.gea.com<https://www.gea.com/en/index.jsp?utm_source=default-signature&utm_medium=link&utm_campaign=email-signature>




GEA INTERNAL
Von: Anton Hokkonen ***@***.***>
Gesendet: Dienstag, 21. September 2021 09:51
An: adewg/ICAR ***@***.***>
Cc: Schultz, Andreas ***@***.***>; Mention ***@***.***>
Betreff: Re: [adewg/ICAR] nullable declaration is not working correctly for reference types (#214)

THIS MESSAGE IS FROM AN EXTERNAL SENDER
________________________________
Please be cautious, particularly with links and attachments.

back to that issue - should we work on correcting nullable declarations in all schemata for the next minor release (1.3?) and then provide a clear and proper descriptions on code generation (at least Java, .NET, TS)?

I can assign that task on myself and verify for .NET gens, but then I'll need an input from the others to make sure we'll get correct output for Java and TS :)

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadewg%2FICAR%2Fissues%2F214%23issuecomment-923728082&data=04%7C01%7Candreas.schultz%40gea.com%7C3b495423b3364f10eb8708d97cd480f7%7C0e17f90f88a34f93a5d7cc847cff307e%7C0%7C0%7C637678074409156285%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RTq6mIJwOqOHg%2FESX9x4%2BFP5RF13Sqt1KJUzxxqj3wY%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATBWSFUBHTACBGY5LPV7WZ3UDA2M3ANCNFSM44EBP5GQ&data=04%7C01%7Candreas.schultz%40gea.com%7C3b495423b3364f10eb8708d97cd480f7%7C0e17f90f88a34f93a5d7cc847cff307e%7C0%7C0%7C637678074409166283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fqtDBkk6oQyQjMPw65wGOK49rPgINzpGxSg5A9u5tlM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Candreas.schultz%40gea.com%7C3b495423b3364f10eb8708d97cd480f7%7C0e17f90f88a34f93a5d7cc847cff307e%7C0%7C0%7C637678074409176277%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=A837FGSCKVuG1AsLJ1vh8srODV1zLsYMbs%2Fos19kRew%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Candreas.schultz%40gea.com%7C3b495423b3364f10eb8708d97cd480f7%7C0e17f90f88a34f93a5d7cc847cff307e%7C0%7C0%7C637678074409176277%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QO4qk7qkhFZD4x9s%2Bvk%2BJ9BiQiSel8phqmh1iSHrwsg%3D&reserved=0>.

**Comment by AndreasSchultzGEA** [comment]
I configured the Java-Generator for the update from 1.1 to 1.2. Now we use the mvn-generator v5.2.1. And as a hint to @alamers :
`                            <configOptions>
                                <dateLibrary>java8</dateLibrary>
                                <openApiNullable>false</openApiNullable>
                            </configOptions>
                            <templateDirectory>${project.basedir}/openapi-generator-templates</templateDirectory>
`
and within the template, we exchanged include = JsonTypeInfo.As.EXISTING_PROPERTY by PROPERTY.

The results are:
Within the 

- Java-code the nullable attributes are initialized with null at their declaration. Nothing more, nothing less. And, there are  @NotNull-Annotations, etc. for non-null attributes located at their getter.
- TypeScript-Code there is nothing left in concerns of the non-/nullability. I'll have to check this generator next.

Does anybody have a configuration which contains more?

**Comment by ahokkonen** [comment]
PR with the fix is published, code generation tested for .NET and typescript.

**Comment by ahokkonen** [comment]
PR is merged and we only need a last Java verification before closing this issue

**Comment by AndreasSchultzGEA** [comment]
Java & JS code generation seems to be okay.

**Comment by ahokkonen** [comment]
seems like all is good, closing this tissue

**Comment by franzose** [comment]
> With some research, things around Nullable types gets even more complicated. With defining complex reference type having just a "nullable: true" is actually not right (and not spec compliant on OAS3.0), but somehow supported by various generators :)
> 
> Here is a nice [issue to read ](https://github.com/OpenAPITools/openapi-generator/issues/5180) on "openapi-generator" project.
> 
> Had no luck with csharp generator producing proper nullable types only with "nullable: true", but when changed code to use "allOf" (I guess "oneOf" or "anyOf" will also do the trick) from my first message everything went smoothly through.
> 
> "created": {
>     "nullable": true,
>     "allOf": [
>         { "$ref": "../types/icarDateTimeType.json" }
>     ]
> }
> In some feedbacks this is also considered as a workaround and not a "fully official" OAS3.0 spec.

I have finally found the solution! It took me quite a while. Thank you very much :)
