### ISSUE TITLE
Add "icarQuarterId" in the TreamentEventressources?

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#221]
Hi 

We miss the possibility to define the QuarterId for the treatment.

**Comment by erwinspeybroeck** [comment]
It is now defined as 

_
site | string Body site where the treatment was administered
_

This could probably be more elaborated.
In our API we use 

_
positions | [position
string
The position to be treated.
Enum:[&nbsp;LEGS_FRONT_LEFT, LEGS_FRONT_RIGHT, LEGS_REAR_LEFT, LEGS_REAR_RIGHT, UDDER_FRONT_LEFT, UDDER_FRONT_RIGHT, UDDER_REAR_LEFT, UDDER_REAR_RIGHT, OVARIES_LEFT, OVARIES_RIGHT, OVARIES_UNKNOWN&nbsp;]
_

**Comment by cookeac** [comment]
I think we left site as a string because different systems seemed to use a wide range of position coding. I do like this list, but I'm not sure how generally used it would be.

**Comment by cookeac** [comment]
At the most recent meeting we decided that we would investigate whether there was any consistency in the use of treatment location (treatment method can be specified using the *procedure* attribute). If there is international consistency, it would be useful to define an enumeration for the *site* attribute, otherwise it may be better used as a string in the standard and extended with a valid list only for local/national use.

**Comment by cookeac** [comment]
Agreed we should add a new field, such as "treatmentSites" - an array of enumerated strings.
"site" will remain for people who just record a text description.
