### ISSUE TITLE
Resource for ReproPreExamintion?

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#233]
Hi, 

When an animal haven´t startet the reproductive cycle. The AI technician can examinate the animal and conclude a status like, the animal is cystic or another remark. The remarks are also sometime registered related to a unsuccesful insemination, ex. in case the animal was post heat and have bleed.
These remarks would be good have in a ressource, the remarks are valuable information for the management of the reproduction in the herd. 

The resource could be like this: 

  "allOf": [{
      "$ref": "../resources/icarEventCoreResource.json"
    },
    {
        "type": "object",
        "properties": {
            "remark": {
                "type": "array",
                 items": {
                 "type": "string" (or maybe a ID and Sheme or an enum?) 
                  }
            }
        }
    
I can see that ReproStatusObservedEventResource maybe could be used with the same purpose, but I miss the possibility to add remarks also. 

Or how do you suggest us to display this kind of info?

**Comment by cookeac** [comment]
I agree that **icarReproStatusObservedEventResource** would be ideal, but in the context of this and other requests, I think there would be value in adding a `remark : string` field to **icarEventCoreResource** so that it is available for all resources.

**Comment by dirbSEGES** [comment]
Yes, that will be valuable. I like this solution.

**Comment by erwinspeybroeck** [comment]
We started collecting remarks in one of our apps since a year now. The remarks are not stored in our backend. We wanted first to get some insight in how the customer would use this remark. We are planning an analysis of what has been entered until now. We want to see if we can standardize remarks instead of black box strings. The advantage of standized remarks would be that you can also do something with this remark  for managment information purpose.
We implemented remarks there for most of the events (in the app, not yet in the API), so indeed a remark in the core resource ould suite best.
