### ISSUE TITLE
Fix request for spectral linter

### ISSUE THREAD

**Issue by ahokkonen** [adewg/ICAR#270]
New version of spectral linter requires ruleset parameter.
Creating default ruleset as part of the sources to solve that issue.

**Comment by cookeac** [comment]
@ahokkonen it doesn't look like that PR quite worked. The message is now:
`Cannot find module '/usr/src/spectral/{{env.SPECTRAL_RULESET_PATH}}'`

**Comment by ahokkonen** [comment]
@cookeac legendary- working on my machine :)
I will look into it

**Comment by alamers** [comment]
I've encountered this one as well (and it still seems to be an issue). 

In my branch, I've fixed the paths but I get this very descriptive error message:

```
Arjans-MacBook-Pro:ICAR arjanl$ docker run stoplight/spectral:6.4.1 lint  https://raw.githubusercontent.com/alamers/ICAR/issue293/url-schemes/exampleUrlScheme.json -r=https://raw.githubusercontent.com/alamers/ICAR/issue293/.spectral.yaml  --verbose
Error running Spectral!
Error #1: [object Object]
Error #2: [object Object]
Error #3: [object Object]
Error #4: [object Object]
Error #5: [object Object]
```

No clue how to continue along this path. Now testing with a default spectral github action (instead of relying on that docker image).

**Comment by alamers** [comment]
Yep, the action does work (but now fails with proper validation errors). I'll create a pull request.

**Comment by alamers** [comment]
Well... it does a bit more but I have no clue where it leaves its output. Maybe we should simply remove it and rely on speccy only?

**Comment by alamers** [comment]
The speccy validations fails also by the way, but that doesn't stop the build (and still gives a green light..)

**Comment by cookeac** [comment]
At our meeting 2022-08-25 we agreed:
- Spectral is a better linter and works well in individual development environments
- However Spectral is really not working in GitHub, regardless of whether with the official GitHub action or using an image.
- @alamers will attempt to remove or deactivate these actions.

**Comment by cookeac** [comment]
I found that spectral gives an incorrect error about an invalid array item type.
However, the error is actually caused by an error in the array item included by $ref, or by another object within that included by $ref. This can be a bit tricky to find, but when the error is corrected, the spectral error goes away.
I think that because validation further down fails, the type included by $ref is no longer an object, hence the invalid array type.

I have installed the spectral validator component into VS Code and used it to clean up files before doing a PR/merge.
