### ISSUE TITLE
expected calving date

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#275]
Hi 

Have there been a discussion about the information about excepted calving date?  

The same with dryoffdate? 

Or is it up till the client to calculate this? 

BR
Ditlev

**Comment by cookeac** [comment]
Consider using the Gestations API and resource type which allows this to be calculated and delivered by the server. The Lactation resource could potentially be extended with expected drying off date if that was helpful?

**Comment by erwinspeybroeck** [comment]
We are using "indication" API's for this to support our apps
We have the following API's
/{market-country-code}/customer/{customer-id}/indications/calvings - this gives a working list for animals that will calve
/{market-country-code}/customer/{customer-id}/indications/heats - this gives the animals to be checked for heat
/{market-country-code}/customer/{customer-id}/indications/runnings-with-a-bull - list of running with a bull without an end date
/{market-country-code}/customer/{customer-id}/indications/deviations - a worklist with animals to be checked. Animals which are on the list because they are late for heats or impregnations after calving.
/{market-country-code}/customer/{customer-id}/indications/gestations - A worklist with animals to be checked for gestations. Animals for which an pregnancycheck date is calculated

We use settings on customer/location level, e.g. Days for pregnancy check after impregnation, days before calving to dry off

The response can differ from API to API. 
We mostly have:
- animal Id
- expected date (calving, preg check, heat)
- we also have a manually adde section - farmers can manually add checks they want to do

Should we explore this more to derive some standard out of it?

**Comment by dirbSEGES** [comment]
Hi, 
Thank you for your answers. 
I see now that Gestations handles expected calvingdate. Haven´t seen that. Sorry. 
And in combination with Lactation ressource we have DIM and if this could extended with expected Dryoff date, it will be helpful. 

We also have system setting for expected calving and user setting(location) for expected dryoff, so I want to use this settings so the user/farmer do not get different date(calculations) in the various clients he use. 

We have the same worklist also, as mentioned, so maybe it a consideration to have a ressource for this kind of "indications", again so the farmer/user can see the same settings in various clients.
