### ISSUE TITLE
Events following the animal

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#276]
Hi, 
What is the recommendations about how the events following an animal are displayed in the ressources? 

Ex. We use a location as parameter to find all parturitions created on the given location. The same location have purchased some animals  with parturions created on a different location. 

Should this events be displayed at the current location? 

Or is just optionel what we dicedes? 

BR

**Comment by cookeac** [comment]
Hi Ditlev,

A very good question. The short answer is that this is up to your implementation and not specified by the interface specifications.

However, based on my experience, I'd make the following recommendations:
* The actual location on which events were recorded should not change when an animal moves from one location to another. This is a good reason why location should be added to resources as per #267. 
* Providing the seller and the buyer of animals agree, ideally events recorded on previous locations should "move" or be available to the buyer of the animals. However, this doesn't always happen.
* There may be implications for how some organisations operate their data access controls, which is why this is implementation dependent.
* If events from previous locations IS available (for instance, mating, parturition), then calculated or summary data for the new location should make use of this. For instance, Gestations or Lactations on the new location could use event data (where available) from the previous location to calculate information for the current location.

**Comment by dirbSEGES** [comment]
Hi Andrew, 

Thank you for your answer. 

We will take an internal discussion about this. We have all the data available. 

I will closed this issue.
