### ISSUE TITLE
Provide predictions for expected milk yield

### ISSUE THREAD

**Issue by dirbSEGES** [adewg/ICAR#285]
Hi, 

Could TestDayResultEventResource have a new property:   "milkWeightExpected" or "milkWeightGoal" ? 

BR

**Comment by cookeac** [comment]
We agree we should add `milkWeight24HoursPredicted`.
It would also be useful to consider how predictions are interchanged more generally.

**Comment by cookeac** [comment]
Erwin will investigate this.

**Comment by erwinspeybroeck** [comment]
1) it is possible to add predicted fields to the test day result API - on our database they are called:
- milkWeightExpected
- fatWeightExpected
- ProteinWeightExpected
Andrews proposal is maybe better since it makes clear that it 's a 24 hours expected weight
- milkWeight24HoursPredicted
- fatWeight24HoursPredicted
- proteinWeight24HoursPredicted

2) we deliver now to feeding companies also milk-predictions
This contains in fact information (milk, fat and protein) about the expected lactation curve:
- expected average 24  hour production for the rest of the lactation (end based on expected calving date)
- if the peak of the lactation still has to occur : the exact days in milk the peak will be reached and the predicted 24 h production on that peak
- the predicted 24h production on the next (in the future) milk recording (if no info about when - 3 weeks is taken as interval

Do we need to define an ICAR standard API for this?  I will need it to phase out some old software. I might define it for now in the way we want to provide this information to our customers. Has naybody else such kind of information they share at this moment?

**Comment by cookeac** [comment]
We discussed at our meeting on 2022-08-25 and agreed that it would make sense to have a message such as that described in option 2 - a more generalised lactation prediction for individual animals. We wondered if this might avoid having to have prediction fields in the test day resource. However, if the lactation prediction was always future-focused, you could then lose the previous prediction for the test day, and not be able to compare it.
@erwinspeybroeck will start to model this up (code, diagram, or documentation - any is fine) and we will review and discuss at a future meeting.

**Comment by erwinspeybroeck** [comment]
I did the following:

- added predicted fields to the test day result resource
- added a new resource "milkPrediction"
- added it for the moment in the milk url only

It can be viewed by https://editor.swagger.io/?url=https://raw.githubusercontent.com/adewg/ICAR/erwinspeybroeck/url-schemes/milkURLScheme.json

**Comment by cookeac** [comment]
On 2022-11-03 @erwinspeybroeck took us through the excellent and very interesting API design for this.
We agreed:
* It would be useful to define a MilkPrediction type which could contain the periodHours (usually 24 hours), and three `icarMilkingMilkWeightType` objects - one for milkWeight, one for fatWeight, and one for proteinWeight.
* The names of the predicted average rest of lactation and predicted for next milk recording could then be clearer.
