### ISSUE TITLE
Group assignments missing (feeding, milking, barn)

### ISSUE THREAD

**Issue by thomasd-gea** [adewg/ICAR#88]
During the process of implementing a data exchange using the ICAR format we recognized that animals cannot be assigned to groups right now. In our use case animals can be assigned to specific groups to define how they are fed, milked and in which barn area they are located.

A possible integration of that into the ICAR standard could be:
- add a new resource "animal group" that has the attributes "type" as an enumerated value (e.g. "FEEDING", "MILKING", "BARN") and "name" which describes the group as a string value
- allow for CRUD on the new resource type
- add a new attribute "assigned groups" to the animal that consists of a list of "animal groups"

**Comment by MetroMarv** [comment]
First minimal proposal for a animal set resource. We use the term "set" instead of "groups" here, because it's more generic.

**Comment by cookeac** [comment]
@thomasd-gea @MetroMarv I'm currently reviewing PR #127 and I note that "type" does not have an enumeration defined (compare with the comment in the issue above regarding standard types). It is probably not useful without either an enumeration or a ID scheme (and I think an enumeration should be suitable initially).

Also I propose renaming the field from "**type**" to "**purpose**", only because otherwise the enumeration file will be called *icarAnimalSetTypeType.json*! This way it would be called *icarAnimalSetPurposeType.json*.

Some ideas of enumerated values:
| Value | Meaning |
| ------ | ---------- |
| Feeding | Used to manage different feeding regimes. |
| Health | Used to manage different health treatments. |
| Reproduction | Used to manage reproduction - for instance, mating group. |
| Lactation | Used to manage lactation - for instance, milking or drying off groups. |
| Movement | A group of animals are being moved together between locations (e.g. arrival, departure...) |
| Enclosure | A group of animals being kept together - in a barn, pen, or paddock. |
| Session | A group of animals being observed or handled together - for instance, a weighing session. |
