### ISSUE TITLE
breeding values of an animal API

### ISSUE THREAD

**Issue by erwinspeybroeck** [adewg/ICAR#89]
I want to start working on a proposal for breeding values of an animal

We are using right now :

**animalId** :  unique identification code of an animal - identifier and scheme
**base** :  base string breeding value calculation 
             Enum:[ GES_BLACK_AND_WHITE, GES_RED_AND_WHITE, GES_LOCAL, GES_BELGIAN_BLUE, 
             US_NL_COMBINED, US_HOLSTEIN, US_JERSEY, UNKNOWN ]
maybe we can also use a scheme and id for the base - the enum above would be the scheme used by CRV
**breedingValues**  - array of breedingValue
-- **scheme/id** : the scheme and the id of the breeding value
-- **name** : name of the breeding value.
-- **calculationType**: mathematical method used 
             Enum:[ breeding value, parent average, parent average derived, MRY-DN, Genomic breeding 
             value, interbull breeding value, converted breeding value, Sire-MGS average, Sire-country 
             average, Country average, unknown ]
-- **value**: integer numeric value of an object
-- **reliability**: number statistical reliability of the breeding value

**Comment by cookeac** [comment]
We developed a specification for "Merits" (a generic term for breeding values, indexes, and other calculated individual animal predictions of merit) as part of the DataLinker project. It has been implemented by some organisations in NZ and Australia. 

I think it would be pretty easy to fit into the ICAR schema, looking something like a lactation, and with a Scheme and ID approach to identifying the particular breeding value or merit.

**Comment by cookeac** [comment]
It seems to me there are several entities to be considered. Most of these will probably not be resources, just worth identifying in some way:
1. The provider or formal type of analysis. For instance, this might be an ICAR international analysis, or a within country analysis, or a within breed analysis, or an analysis from a specific provider. This seems similar to the BASE specified above. I think that a scheme or URL would be a good way to represent this.
2. The analysis version or date. Many analyses are run weekly, monthly, annually. It is important to know which set of breeding values you are looking at - is it the latest?
3. The trait which the breeding value represents. The scheme/id mechanism proposed for this is good, but perhaps if the ID was a URL or reference to a definition resource, then things like meaning and internationalisation could be addressed in this definition rather than in the data for every animal. For instance we did this: https://github.com/Datalinker-Org/Animal-Data/blob/master/Merits_Traits_and_Sessions/MeritDefinition.md

I also note that this approach could be used for other things than breeding values. For instance, a combined index (summing several breeding values multiplied by economic values), or other values that are calculated similarly to breeding values but not for breeding purposes (such as stress or health merits).

**Comment by erwinspeybroeck** [comment]
1. Indeed, we can determine a scheme or url for this. E.g. nl.ges.black_and_white
2. My proposal was to only return the latest available - so you know when you retrieve it that you have the latest. Most people are not interested in previous versions. But for information of the version like it is known by the provider, this would be usefull
3. Good idea, but might be more work?

**Comment by erwinspeybroeck** [comment]
**animalId** : unique identification code of an animal - identifier and scheme
**base** : id + scheme of the base of the breeding value
**version** : string which sets the version for the breeding value estimation - this can be a date, or a version name, or something the calculation center is using to identify their seperate runs.
**breedingValues** - array of breedingValue
-- **traitLabel** : the scheme and id of the trait for which a breeding value is calculated
-- **calculationType**: mathematical method used : Enum:[ breedingValue, parentAverage, genomicBreedingValue, convertedBreedingValue, Other ]
-- **value**: numeric (decimal) value of an object
-- **reliability**: numeric (decimal) statistical reliability of the breeding value
-- **resolution**: The smallest difference that is relevant for this breeding value (to guide display) to assist in the interpretation of floating point values

**Comment by cookeac** [comment]
Suggest adding:
-- **resolution**:  The smallest difference that is relevant for this breeding value (to guide display).

**Comment by craigv** [comment]
I got some feedback from a geneticist here:
The value isn't always an integer, think of docility or protein %. **Maybe allow a float there**.
Some existing Interbull files get around this by multiplying everything by either 100 or 1000 depending on trait.

**Comment by cookeac** [comment]
Agreed, most NZ breeding **values** I have seen are floats. Hence also the suggestion of adding **resolution** to assist interpretation of floating point values (as JSON is not otherwise great at retainining intended decimal places). Note that **reliability** should also be a floating point number.

**Comment by erwinspeybroeck** [comment]
The data type "number" in the json definition has the following characteristics
- Represented in base 10 with no superfluous leading zero (e.g. 000088).
- These include digits between 0 and 9.
- It can be a negative number (e.g. -10.
- It can be a fraction (e.g. .5).
- It can also have an exponent of 10, prefixed by e.
So "number" would cover the remarks above
