### ISSUE TITLE
Changes log/Release notes in ADE release versions

### ISSUE THREAD

**Issue by ahokkonen** [adewg/ICAR#99]
We can use RN generation tool (for example [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator)) or do it manually while creating release. Still it is important to have all changes and related issues been marked into PR/commits (refer to [guide](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))

**Comment by alamers** [comment]
I'm documenting the steps I took for creating the releases, so we can do it consistently:
prepare:
- gem install github_changelog_generator
- create a github token ([github generator token](https://github.com/settings/tokens/new?description=GitHub%20Changelog%20Generator%20token))
-- you only need "repo" scope for private repositories

- merge the pull requests that need to go into the release
- go to https://github.com/adewg/ICAR/releases 
- create a 'release' and name it according to the semantic versioning scheme: e.g. v1.0.1
- I added a simple description 'bugfix release' since details will be in the changelog
- run `github_changelog_generator -u adewg -p ICAR --token <token>`
- copy the generated `CHANGELOG.md` to your repo and push it to Develop
- create a pull request for `ADE-1`

**Comment by alamers** [comment]
I am reviving this ticket since we are close to releasing 1.2 :)

The technical procedure is described above, but probably needs some updating.

**Comment by alamers** [comment]
The technical procedure is described above; deciding on _when_ to do a release and if it is good enough is part of the discussion in the working group. We discussed some quality checks in #207 that we need to embed in this release procedure.
